kind = "mobile"
previewPath = "/"
title = "SplitEasy"
version = "1.0.0"
id = "artifacts/spliteasy"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24816

[services.development]
run = "pnpm --filter @workspace/spliteasy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/spliteasy", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/spliteasy", "run", "serve" ]

[services.env]
PORT = "24816"
BASE_PATH = "/"
